name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Run linters
      run: |
        python -m pip install ruff
        python -m ruff format . --check
        python -m ruff check .

  test:
    needs: lint
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: |
        python -m pip install .[test]
        python -m unittest discover tests

  build-and-deploy:
    needs: test
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Build dists
      run: |
        python -m pip install build
        python -m build .
    - uses: pypa/gh-action-pypi-publish@release/v1
